version: "3.8"

services:
  appserver:
    image: tgmti/totvs-appserver-sqlite
    ports:
      - "1234:1234"
      - "8080:80"
      - "8081:81"
      - "21:21"
    env_file: .env
    volumes:
      - type: bind
        source: ./totvs_volume/apo
        target: /totvs/protheus/apo/
      - type: bind
        source: ./totvs_volume/protheus_data
        target: /totvs/protheus_data

  license:
    image: tgmti/totvs-license
    ports:
      - "5555:5555"

volumes:
  pg_data: {}
